application: django-google-cloud-sql
version: 1
runtime: python
api_version: 1

builtins:
- remote_api: on
- appstats: on 

inbound_services:
- warmup




handlers:
- url: /static
  static_dir: static

- url: /_ah/queue/deferred
  script: djangoappengine_rdbms/deferred/handler.py
  login: admin

- url: /_ah/stats/.*
  script: djangoappengine_rdbms/appstats/ui.py

- url: /media/admin
  static_dir: django/contrib/admin/media
  expiration: '0'

- url: /.*
  script: djangoappengine_rdbms/main/main.py
